version: '3.8'
services:
  app:
    image: ecommerce-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://root:bCFhRIwhWEshLCkOAhFteuxMLxHinTrI@junction.proxy.rlwy.net:45956/railway
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=bCFhRIwhWEshLCkOAhFteuxMLxHinTrI
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - JWT_SECRET_KEY=bWkgY2xhdmUgZXMgbXV5IHNlZ3VyYSAxMjM0NTY3IGFiY2RlZmc=
      - MAIL_USERNAME=innovatechxcorp@gmail.com
      - MAIL_PASSWORD=qboezzvxttvexqyq
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect

